language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_install:
- npm install -g bower
- npm install -g grunt-cli
install:
- npm install
- bower install
before_script:
- grunt build
after_success:
- git config user.name "Travis CI"
- git config user.email "travis@localhost.localdomain"
- grunt gh-pages:travis
env:
  global:
    secure: "XoU8w34o/QJ7QC0vESSep0yiwmHUgHte31lix2R4PXmUIjizG1U031dsUx005sF2ZkPzt9OHDmLYI4e3AfERvPgdVU1jinw217ZiM0oZvjjT7f/fKU9VDwuCM7tqucBUeSPaoXvxjShMLZoUdZ7yegmYKXKYLCVJVddwDjz+Qeg="
